import { TableState } from "../types/Table";

export const initialState: TableState = {
  list: [
    {
      id: "1",
      number: 1,
      status: "free",
      assignedWaiter: "null",
      orders: [],
      totalPriceWithoutTVSH: 0,
      tvsh: 0,
      totalPriceWithTVSH: 0,
      currency: "€",
      billNumber: null,
      printedAt: null,
    },
    {
      id: "2",
      number: 2,
      status: "free",
      assignedWaiter: "null",
      orders: [],
      totalPriceWithoutTVSH: 0,
      tvsh: 0,
      totalPriceWithTVSH: 0,
      currency: "€",
      billNumber: null,
      printedAt: null,
    },
    {
      id: "3",
      number: 3,
      status: "free",
      assignedWaiter: "null",
      orders: [],
      totalPriceWithoutTVSH: 0,
      tvsh: 0,
      totalPriceWithTVSH: 0,
      currency: "€",
      billNumber: null,
      printedAt: null,
    },

    // TABLE 4
    {
      id: "4",
      number: 4,
      status: "waiting",
      assignedWaiter: "null",
      orders: [
        { id: "1", name: "Pizza Margherita", quantity: 2, price: 12, total: 24, round: 1 },
        { id: "2", name: "Coke", quantity: 2, price: 2.5, total: 5, round: 1 },
        { id: "3", name: "Salad", quantity: 1, price: 5, total: 5, round: 1 },
        { id: "4", name: "Pasta Carbonara", quantity: 1, price: 10, total: 10, round: 2 },
        { id: "5", name: "Lemonade", quantity: 1, price: 3, total: 3, round: 2 },
        { id: "6", name: "Tiramisu", quantity: 1, price: 6, total: 6, round: 3 },
        { id: "7", name: "Espresso", quantity: 1, price: 2.1, total: 2.1, round: 3 },
        { id: "8", name: "Water", quantity: 1, price: 1, total: 1, round: 3 },
      ],
      totalPriceWithoutTVSH: 56.1,
      tvsh: 11.22,
      totalPriceWithTVSH: 67.32,
      currency: "€",
      billNumber: "BILL-004",
      printedAt: "2025-01-15T12:40:00Z",
    },

    // TABLE 5
    {
      id: "5",
      number: 5,
      status: "taken",
      assignedWaiter: "Kristiana Trupja",
      orders: [
        { id: "1", name: "Sushi Roll", quantity: 1, price: 15, total: 15, round: 1 },
        { id: "2", name: "Water", quantity: 1, price: 1, total: 1, round: 1 },
        { id: "3", name: "Miso Soup", quantity: 2, price: 4, total: 8, round: 2 },
        { id: "4", name: "Green Tea", quantity: 1, price: 3, total: 3, round: 2 },
        { id: "5", name: "Tempura", quantity: 1, price: 8, total: 8, round: 3 },
      ],
      totalPriceWithoutTVSH: 35,
      tvsh: 7,
      totalPriceWithTVSH: 42,
      currency: "€",
      billNumber: "BILL-005",
      printedAt: null,
    },

    // TABLE 6
    {
      id: "6",
      number: 6,
      status: "served",
      assignedWaiter: "Relando Vrapi",
      orders: [
        { id: "1", name: "Sushi Roll", quantity: 1, price: 15, total: 15, round: 1 },
        { id: "2", name: "Water", quantity: 1, price: 1, total: 1, round: 1 },
        { id: "3", name: "Miso Soup", quantity: 2, price: 4, total: 8, round: 1 },
        { id: "4", name: "Green Tea", quantity: 1, price: 3, total: 3, round: 1 },
      ],
      totalPriceWithoutTVSH: 27,
      tvsh: 5.4,
      totalPriceWithTVSH: 32.4,
      currency: "€",
      billNumber: "BILL-006",
      printedAt: "2025-01-12T10:15:00Z",
    },

    // TABLE 7
    {
      id: "7",
      number: 7,
      status: "served",
      assignedWaiter: "Kristiana Trupja",
      orders: [
        { id: "1", name: "Sushi Roll", quantity: 1, price: 15, total: 15, round: 1 },
        { id: "2", name: "Water", quantity: 1, price: 1, total: 1, round: 1 },
      ],
      totalPriceWithoutTVSH: 16,
      tvsh: 3.2,
      totalPriceWithTVSH: 19.2,
      currency: "€",
      billNumber: "BILL-007",
      printedAt: "2025-01-10T14:00:00Z",
    },

    // TABLE 8
    {
      id: "8",
      number: 8,
      status: "served",
      assignedWaiter: "Jetmir Ahmati",
      orders: [
        { id: "1", name: "Sushi Roll", quantity: 1, price: 15, total: 15, round: 1 },
        { id: "2", name: "Water", quantity: 1, price: 1, total: 1, round: 1 },
      ],
      totalPriceWithoutTVSH: 16,
      tvsh: 3.2,
      totalPriceWithTVSH: 19.2,
      currency: "€",
      billNumber: "BILL-008",
      printedAt: "2025-01-09T18:30:00Z",
    },
  ],
};